include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"

  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat missing required params as errors
    missing_required_param: error
    # Treat using deprecated members as warnings
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    # Additional rules beyond flutter_lints

    # Style
    - always_use_package_imports
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - sort_constructors_first
    - use_super_parameters

    # Error prevention
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements

    # Performance
    - avoid_function_literals_in_foreach_calls
    - prefer_foreach
