name: my_games_list
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  mobx_codegen: ^2.7.4

flutter:
  uses-material-design: true
