name: my_games_list
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  get_it: ^8.2.0
  go_router: ^16.2.4
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  equatable: ^2.0.7
  validatorless: ^1.2.5
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
