// GENERATED FILE - DO NOT EDIT MANUALLY
//
// This file is generated by running:
//   flutterfire configure --project=mygameslist-production --out=lib/firebase_options_production.dart
//
// See FIREBASE_SETUP.md for setup instructions.

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: ProductionFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  ProductionFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    // TODO: Run `flutterfire configure --project=mygameslist-production --out=lib/firebase_options_production.dart`
    // to generate the real configuration for this file.
    throw UnsupportedError(
      'ProductionFirebaseOptions not configured. '
      'Run flutterfire configure to generate this file. '
      'See FIREBASE_SETUP.md for instructions.',
    );
  }
}
