// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: ProductionFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGEdrlVoFywfq3pks-ISdpaRXyH3goPI',
    appId: '1:119889981446:web:6e56a7fa0adc0452dd9387',
    messagingSenderId: '119889981446',
    projectId: 'mygameslist-production',
    authDomain: 'mygameslist-production.firebaseapp.com',
    storageBucket: 'mygameslist-production.firebasestorage.app',
    measurementId: 'G-SXLJ0KPHC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjKzCwE1kjju3PHxIh5rFbVYim9qYPQ_M',
    appId: '1:119889981446:android:f0ea35ef76ceaf29dd9387',
    messagingSenderId: '119889981446',
    projectId: 'mygameslist-production',
    storageBucket: 'mygameslist-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNoY5CNn05Lk2dUqlmCm0t8x6VYonwDWQ',
    appId: '1:119889981446:ios:36813c47014a37bbdd9387',
    messagingSenderId: '119889981446',
    projectId: 'mygameslist-production',
    storageBucket: 'mygameslist-production.firebasestorage.app',
    iosClientId: '119889981446-h1pdtt4fnfupcv6f20qhurhaq6bahjce.apps.googleusercontent.com',
    iosBundleId: 'com.elberte.mygameslist',
  );

}