// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: StagingFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV8fiXyKvbQrfYuTfWBSMjupr2lHGPMIM',
    appId: '1:916696334729:web:832d32110ad27f6b93e158',
    messagingSenderId: '916696334729',
    projectId: 'mygameslist-staging',
    authDomain: 'mygameslist-staging.firebaseapp.com',
    storageBucket: 'mygameslist-staging.firebasestorage.app',
    measurementId: 'G-W002286Q42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwdZhBFQS4NXo7LIYvaTao3zq_EVtxlo',
    appId: '1:916696334729:android:041ab40e9756cf8f93e158',
    messagingSenderId: '916696334729',
    projectId: 'mygameslist-staging',
    storageBucket: 'mygameslist-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw9r09K907HRkboit1ub2WpkksqzFPTDE',
    appId: '1:916696334729:ios:794568b005fae27993e158',
    messagingSenderId: '916696334729',
    projectId: 'mygameslist-staging',
    storageBucket: 'mygameslist-staging.firebasestorage.app',
    iosClientId:
        '916696334729-q9j8ogeuukcmcp2adr0l62bvce0smtsq.apps.googleusercontent.com',
    iosBundleId: 'com.elberte.mygameslist',
  );
}
